from __future__ import annotations

import json

AI_WORKSPACE_CSS = r'''
.v2-ai-controls{margin-top:14px;border-top:1px solid rgba(148,163,184,.1);padding-top:13px}.v2-ai-control-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:12px}.v2-control-block{border:1px solid var(--v2-border);border-radius:15px;padding:12px;background:rgba(7,17,31,.36)}.v2-control-block>label{font-size:10px;text-transform:uppercase;letter-spacing:.07em;font-weight:900;color:var(--v2-muted);margin-bottom:7px}.v2-segmented{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.v2-segmented.modes{grid-template-columns:repeat(3,minmax(0,1fr))}.v2-segmented button{border:1px solid var(--v2-border);border-radius:11px;padding:9px 7px;background:rgba(7,17,31,.5);color:var(--v2-muted);font-size:10px;font-weight:800;cursor:pointer}.v2-segmented button.active{color:#ecfeff;border-color:rgba(34,211,238,.38);background:linear-gradient(135deg,rgba(34,211,238,.13),rgba(139,92,246,.11))}.v2-segmented button:disabled{opacity:.42;cursor:not-allowed}.v2-command-compose{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;margin-top:11px}.v2-command-compose textarea{min-height:74px;resize:vertical}.v2-command-result{margin-top:8px;border:1px solid rgba(148,163,184,.1);border-radius:12px;padding:9px 10px;color:var(--v2-muted);font-size:10px;background:rgba(5,13,24,.35)}.v2-command-result b{color:#dcecff}.v2-gateway-lock{display:flex;align-items:center;gap:8px;margin-top:10px;padding:9px 10px;border:1px solid rgba(52,211,153,.18);border-radius:12px;background:rgba(52,211,153,.06);color:#b7f7d6;font-size:10px}.v2-gateway-lock::before{content:"✓";display:grid;place-items:center;width:20px;height:20px;border-radius:50%;background:rgba(52,211,153,.14);font-weight:900}
@media(max-width:900px){.v2-ai-control-grid{grid-template-columns:1fr}}@media(max-width:560px){.v2-segmented{grid-template-columns:1fr 1fr}.v2-segmented.modes{grid-template-columns:1fr}.v2-command-compose{grid-template-columns:1fr}}
'''

AI_WORKSPACE_JS = r'''
(()=>{
  const keyProvider='yca.eliteV2.provider',keyMode='yca.eliteV2.mode';
  const classify=text=>{const v=(' '+String(text||'').toLocaleLowerCase('pt-BR')+' ');if(/\b(excluir|deletar|apagar|delete)\b/.test(v))return['Solicitação destrutiva','Requer confirmação específica do alvo. Nenhuma exclusão será executada aqui.'];if(/\b(playlist|lista de reprodução)\b/.test(v)&&/\b(criar|organizar|mover|adicionar|sugerir)\b/.test(v))return['Proposta de playlist','Pode coletar fatos e montar uma proposta. Escrita continua bloqueada até aprovação.'];if(/\b(publicar|upload|agendar|schedule)\b/.test(v))return['Preparação de publicação','Pode preparar dados e preview. Publicação exige confirmação explícita.'];if(/(título|titulo|descrição|descricao|\btag\b|\bseo\b|otimizar)/.test(v))return['Proposta de metadados','Pode sugerir título, descrição, tags e SEO sem aplicar automaticamente.'];if(/(analisar|auditar|diagnóstico|diagnostico|crescimento|analytics|por que)/.test(v))return['Análise somente leitura','Pode usar dados oficiais/cache e explicar o diagnóstico.'];return['Comando não classificado','Nenhuma ação será executada até o objetivo ficar claro.']};
  const install=()=>{const host=document.querySelector('[data-v2-ai-workspace]');if(!host||host.querySelector('[data-v2-ai-controls]'))return false;const controls=document.createElement('div');controls.className='v2-ai-controls';controls.dataset.v2AiControls='1';controls.innerHTML=`<div class="v2-ai-control-grid"><div class="v2-control-block"><label>Motor preferido</label><div class="v2-segmented" data-v2-provider-select><button data-value="local">IA Local</button><button data-value="internal">Interno</button><button data-value="chatgpt">ChatGPT</button><button data-value="api">API</button></div></div><div class="v2-control-block"><label>Modo operacional</label><div class="v2-segmented modes" data-v2-mode-select><button data-value="manual">Manual</button><button data-value="assisted">Assistido</button><button data-value="supervised">Supervisionado</button></div></div></div><div class="v2-command-compose"><textarea data-v2-command-input placeholder="Ex.: analise meus vídeos em queda e proponha melhorias de título, sem aplicar nada"></textarea><button class="btn primary" type="button" data-v2-command-plan>Interpretar comando</button></div><div class="v2-command-result" data-v2-command-result><b>Pronto para planejar.</b> O comando será classificado localmente antes de qualquer chamada de IA.</div><div class="v2-gateway-lock">Toda alteração mutável permanece atrás de preview, aprovação explícita, readback e auditoria do Write Gateway.</div>`;host.appendChild(controls);
    const providerButtons=[...controls.querySelectorAll('[data-v2-provider-select] button')],modeButtons=[...controls.querySelectorAll('[data-v2-mode-select] button')];const mark=(buttons,value)=>buttons.forEach(b=>b.classList.toggle('active',b.dataset.value===value));
    const storedProvider=localStorage.getItem(keyProvider)||'local',storedMode=localStorage.getItem(keyMode)||'assisted';mark(providerButtons,storedProvider);mark(modeButtons,storedMode);
    providerButtons.forEach(b=>b.addEventListener('click',()=>{localStorage.setItem(keyProvider,b.dataset.value);mark(providerButtons,b.dataset.value)}));modeButtons.forEach(b=>b.addEventListener('click',()=>{localStorage.setItem(keyMode,b.dataset.value);mark(modeButtons,b.dataset.value)}));
    controls.querySelector('[data-v2-command-plan]').addEventListener('click',()=>{const [intent,policy]=classify(controls.querySelector('[data-v2-command-input]').value),provider=localStorage.getItem(keyProvider)||'local',mode=localStorage.getItem(keyMode)||'assisted';controls.querySelector('[data-v2-command-result]').innerHTML=`<b>${intent}</b> · motor: ${provider} · modo: ${mode}. ${policy}`});return true};
  if(!install()){const observer=new MutationObserver(()=>{if(install())observer.disconnect()});observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),8000)}
})();
'''


def ai_workspace_webengine_source() -> str:
    css_json = json.dumps(AI_WORKSPACE_CSS, ensure_ascii=False)
    return (
        "(()=>{if(!document.querySelector('style[data-yca-v2-ai-controls]')){"
        "const s=document.createElement('style');s.dataset.ycaV2AiControls='1';"
        f"s.textContent={css_json};(document.head||document.documentElement).appendChild(s);"
        "}})();\n" + AI_WORKSPACE_JS
    )
