from __future__ import annotations

import json

SEO_UI_CSS = r'''
.v2-seo-lab{grid-column:1/-1;border:1px solid var(--v2-border);border-radius:20px;padding:17px;background:linear-gradient(145deg,rgba(18,31,50,.93),rgba(8,17,30,.95));box-shadow:var(--v2-shadow)}.v2-seo-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.v2-seo-head h3{margin:0;font-size:16px}.v2-seo-head p{margin:4px 0 0;color:var(--v2-muted);font-size:11px;max-width:760px}.v2-seo-tools{display:flex;gap:7px;align-items:end;flex-wrap:wrap}.v2-seo-tools label{min-width:210px}.v2-seo-result{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:13px}.v2-seo-signal{border:1px solid rgba(148,163,184,.12);border-radius:14px;padding:12px;background:rgba(5,13,24,.38);min-height:125px}.v2-seo-signal strong{display:block;font-size:12px;margin-bottom:6px}.v2-seo-signal p{margin:0;color:var(--v2-muted);font-size:10px;line-height:1.45}.v2-seo-signal small{display:inline-flex;margin-top:9px;padding:5px 7px;border-radius:999px;border:1px solid var(--v2-border);font-weight:900;text-transform:uppercase;font-size:8px;letter-spacing:.06em}.v2-seo-signal[data-state="ok"] small{color:#86efac;border-color:rgba(52,211,153,.22)}.v2-seo-signal[data-state="attention"] small{color:#fde68a;border-color:rgba(251,191,36,.22)}.v2-seo-signal[data-state="critical"] small{color:#fda4af;border-color:rgba(251,113,133,.25)}.v2-seo-limitations{margin-top:10px;border-top:1px solid rgba(148,163,184,.09);padding-top:10px;color:var(--v2-muted);font-size:10px}.v2-seo-limitations b{color:#dcecff}@media(max-width:760px){.v2-seo-head{flex-direction:column}.v2-seo-tools{width:100%}.v2-seo-tools label,.v2-seo-tools .btn{flex:1}.v2-seo-result{grid-template-columns:1fr}}
'''

SEO_UI_JS = r'''
(()=>{
  const esc=value=>String(value??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]));
  const install=()=>{if(document.querySelector('[data-v2-seo-lab]'))return;const section=document.getElementById('strategy'),grid=section&&section.querySelector('.grid');if(!grid)return;const growth=grid.querySelector('[data-v2-growth-workspace]');const lab=document.createElement('article');lab.className='v2-seo-lab';lab.dataset.v2SeoLab='1';lab.innerHTML=`<div class="v2-seo-head"><div><h3>SEO & Strategy Lab</h3><p>Diagnóstico explicável de metadados. O laboratório não inventa volume de busca nem CTR quando essas fontes não estão disponíveis.</p></div><div class="v2-seo-tools"><label>Vídeo selecionado<input data-v2-seo-video placeholder="ID do vídeo"></label><button class="btn primary" type="button" data-v2-seo-run>Analisar fatos</button></div></div><div class="v2-seo-result" data-v2-seo-result><div class="v2-growth-empty" style="grid-column:1/-1">Selecione um vídeo no Content Hub ou informe o ID.</div></div><div class="v2-seo-limitations"><b>Separação de evidência:</b> recomendações de SEO são sugestões. Dados oficiais, heurísticas e limitações ficam identificados separadamente.</div>`;if(growth)growth.insertAdjacentElement('afterend',lab);else grid.prepend(lab);
    const input=lab.querySelector('[data-v2-seo-video]'),result=lab.querySelector('[data-v2-seo-result]'),button=lab.querySelector('[data-v2-seo-run]');const sync=()=>{const selected=document.getElementById('videoId')?.value?.trim();if(selected&&!input.value)input.value=selected};document.querySelector('.nav button[data-tab="strategy"]')?.addEventListener('click',()=>setTimeout(sync,80));sync();
    button.addEventListener('click',async()=>{const id=input.value.trim();if(!id){result.innerHTML='<div class="v2-growth-empty" style="grid-column:1/-1">Informe ou selecione um vídeo.</div>';return}button.disabled=true;button.textContent='Analisando…';try{const r=await fetch('/api/v2/seo/video/'+encodeURIComponent(id),{headers:{Accept:'application/json'}}),d=await r.json();if(!r.ok||!d.available)throw new Error(d.detail||'SEO indisponível');const signals=d.analysis?.signals||[];result.innerHTML=signals.map(s=>`<div class="v2-seo-signal" data-state="${esc(s.state)}"><strong>${esc(s.label)}</strong><p>${esc(s.evidence)}${s.recommendation?'<br><br>'+esc(s.recommendation):''}</p><small>${esc(s.state)}</small></div>`).join('')||'<div class="v2-growth-empty" style="grid-column:1/-1">Nenhum sinal retornado.</div>';const limits=d.context?.limitations||[];lab.querySelector('.v2-seo-limitations').innerHTML=`<b>Fonte:</b> ${esc(d.analysis?.source||'desconhecida')} · estimado=${esc(d.analysis?.estimated)}<br>${limits.map(esc).join(' · ')}`}catch(err){result.innerHTML=`<div class="v2-growth-empty" style="grid-column:1/-1">${esc(err.message)}</div>`}finally{button.disabled=false;button.textContent='Analisar fatos'}})
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
'''


def seo_ui_webengine_source() -> str:
    css_json=json.dumps(SEO_UI_CSS,ensure_ascii=False)
    return "(()=>{if(!document.querySelector('style[data-yca-v2-seo]')){const s=document.createElement('style');s.dataset.ycaV2Seo='1';s.textContent="+css_json+";(document.head||document.documentElement).appendChild(s);}})();\n"+SEO_UI_JS
